**Name : Abu Bakar Sadiq**
**Program: AI'B'**
**Task:Week2**

## IRIS Dataset

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation
import pandas as pd

print(pd.__version__)

3.0.2

In [2]:
df=pd.read_csv('data\\iris\\iris.data')

In [3]:
df

     5.1  3.5  1.4  0.2     Iris-setosa
0    4.9  3.0  1.4  0.2     Iris-setosa
1    4.7  3.2  1.3  0.2     Iris-setosa
2    4.6  3.1  1.5  0.2     Iris-setosa
3    5.0  3.6  1.4  0.2     Iris-setosa
4    5.4  3.9  1.7  0.4     Iris-setosa
..   ...  ...  ...  ...             ...
144  6.7  3.0  5.2  2.3  Iris-virginica
145  6.3  2.5  5.0  1.9  Iris-virginica
146  6.5  3.0  5.2  2.0  Iris-virginica
147  6.2  3.4  5.4  2.3  Iris-virginica
148  5.9  3.0  5.1  1.8  Iris-virginica

[149 rows x 5 columns]

In [24]:
columns = ['sepal_length_cm', 'sepal_width_cm', 'petal_length_cm', 'petal_width_cm', 'class']
df.index = range(1, len(df) + 1)
print(df.head())

   sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm  \
1              5.1             3.5              1.4             0.2
2              4.9             3.0              1.4             0.2
3              4.7             3.2              1.3             0.2
4              4.6             3.1              1.5             0.2
5              5.0             3.6              1.4             0.2

         class
1  Iris-setosa
2  Iris-setosa
3  Iris-setosa
4  Iris-setosa
5  Iris-setosa

In [28]:
columns = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'species']
df

,sepal_length_cm,sepal_width_cm,petal_length_cm,petal_width_cm,class
1,5.1,3.5,1.4,0.2,Iris-setosa
2,4.9,3.0,1.4,0.2,Iris-setosa
3,4.7,3.2,1.3,0.2,Iris-setosa
4,4.6,3.1,1.5,0.2,Iris-setosa
5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...
146,6.7,3.0,5.2,2.3,Iris-virginica
147,6.3,2.5,5.0,1.9,Iris-virginica
148,6.5,3.0,5.2,2.0,Iris-virginica
149,6.2,3.4,5.4,2.3,Iris-virginica
150,5.9,3.0,5.1,1.8,Iris-virginica

In [33]:
sepal_lengths = pd.Series(df['sepal_length_cm'].head(5).reset_index(drop=True))

print(sepal_lengths)

print("Number of values:", len(sepal_lengths))
print("Mean:", sepal_lengths.mean())
print("Minimum:", sepal_lengths.min())
print("Maximum:", sepal_lengths.max())

0    5.1
1    4.9
2    4.7
3    4.6
4    5.0
Name: sepal_length_cm, dtype: float64
Number of values: 5
Mean: 4.859999999999999
Minimum: 4.6
Maximum: 5.1

In [35]:
petal_lengths = pd.Series(
    df['petal_length_cm'].head(3).values,
    index=['Flower_1', 'Flower_2', 'Flower_3']
)

print(petal_lengths)
print(petal_lengths['Flower_2'])

Flower_1    1.4
Flower_2    1.4
Flower_3    1.3
dtype: float64
1.4

In [36]:
print(df.shape)

(150, 5)

In [37]:
df.describe()

       sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm
count       150.000000      150.000000       150.000000      150.000000
mean          5.843333        3.054000         3.758667        1.198667
std           0.828066        0.433594         1.764420        0.763161
min           4.300000        2.000000         1.000000        0.100000
25%           5.100000        2.800000         1.600000        0.300000
50%           5.800000        3.000000         4.350000        1.300000
75%           6.400000        3.300000         5.100000        1.800000
max           7.900000        4.400000         6.900000        2.500000

In [38]:
df.isnull().sum()

sepal_length_cm    0
sepal_width_cm     0
petal_length_cm    0
petal_width_cm     0
class              0
dtype: int64

In [39]:
print(df)

print('Rows:', len(df))
print('Columns:', len(df.columns))

     sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm  \
1                5.1             3.5              1.4             0.2
2                4.9             3.0              1.4             0.2
3                4.7             3.2              1.3             0.2
4                4.6             3.1              1.5             0.2
5                5.0             3.6              1.4             0.2
..               ...             ...              ...             ...
146              6.7             3.0              5.2             2.3
147              6.3             2.5              5.0             1.9
148              6.5             3.0              5.2             2.0
149              6.2             3.4              5.4             2.3
150              5.9             3.0              5.1             1.8

              class
1       Iris-setosa
2       Iris-setosa
3       Iris-setosa
4       Iris-setosa
5       Iris-setosa
..              ...
146  Iris-virginica
147  Iris-virginica
148  Iris-virginica
149  Iris-virginica
150  Iris-virginica

[150 rows x 5 columns]
Rows: 150
Columns: 5

In [40]:
print('Index:', df.index)
print('Columns:', list(df.columns))

Index: RangeIndex(start=1, stop=151, step=1)
Columns: ['sepal_length_cm', 'sepal_width_cm', 'petal_length_cm', 'petal_width_cm', 'class']

In [41]:
print(df.duplicated().sum())

3

In [42]:
print(df.dtypes)

sepal_length_cm    float64
sepal_width_cm     float64
petal_length_cm    float64
petal_width_cm     float64
class                  str
dtype: object

In [43]:
print(df[df.duplicated()])

     sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm  \
35               4.9             3.1              1.5             0.1
38               4.9             3.1              1.5             0.1
143              5.8             2.7              5.1             1.9

              class
35      Iris-setosa
38      Iris-setosa
143  Iris-virginica

In [44]:
print(df[df.duplicated(keep=False)])

     sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm  \
10               4.9             3.1              1.5             0.1
35               4.9             3.1              1.5             0.1
38               4.9             3.1              1.5             0.1
102              5.8             2.7              5.1             1.9
143              5.8             2.7              5.1             1.9

              class
10      Iris-setosa
35      Iris-setosa
38      Iris-setosa
102  Iris-virginica
143  Iris-virginica

In [45]:
df = df.drop_duplicates()

In [46]:
print(df.duplicated().sum())

0

In [47]:
df.to_csv('iris.csv', index=False)
print('Saved')

Saved

In [48]:
df2 = pd.read_csv('iris.csv')
print(df2)

     sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm  \
0                5.1             3.5              1.4             0.2
1                4.9             3.0              1.4             0.2
2                4.7             3.2              1.3             0.2
3                4.6             3.1              1.5             0.2
4                5.0             3.6              1.4             0.2
..               ...             ...              ...             ...
142              6.7             3.0              5.2             2.3
143              6.3             2.5              5.0             1.9
144              6.5             3.0              5.2             2.0
145              6.2             3.4              5.4             2.3
146              5.9             3.0              5.1             1.8

              class
0       Iris-setosa
1       Iris-setosa
2       Iris-setosa
3       Iris-setosa
4       Iris-setosa
..              ...
142  Iris-virginica
143  Iris-virginica
144  Iris-virginica
145  Iris-virginica
146  Iris-virginica

[147 rows x 5 columns]

In [49]:
df = pd.read_csv('data/iris/iris.data', names=columns)
print(df.head())

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [50]:
df.to_json('iris.json', orient='records', indent=2)
print('Saved JSON')

Saved JSON

In [51]:
df_json = pd.read_json('iris.json')
print(df_json)

     sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [52]:
print(df.head(3))

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa

In [53]:
print(df.tail(2))

     sepal_length  sepal_width  petal_length  petal_width         species
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

In [54]:
print('Shape:', df.shape)

Shape: (150, 5)

In [55]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    str
dtypes: float64(4), str(1)
memory usage: 7.9 KB

In [56]:
print(df.describe())

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [57]:
print(df.dtypes)

sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
species             str
dtype: object

In [58]:
print(df.head())
print(df.tail())
print(df.shape)
print(list(df.columns))
df.info()
print(df.describe())
print(df.dtypes)

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa
     sepal_length  sepal_width  petal_length  petal_width         species
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica
(150, 5)
['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'species']
<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    str
dtypes: float64(4), str(1)
memory usage: 7.9 KB
       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000
sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
species             str
dtype: object

In [59]:
missing = df.isnull().sum()
print(missing)

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [60]:
print(df.duplicated().sum())

3

In [63]:
result = df[df['petal_length'] >= 5.0]
print(result)

     sepal_length  sepal_width  petal_length  petal_width          species
77            6.7          3.0           5.0          1.7  Iris-versicolor
83            6.0          2.7           5.1          1.6  Iris-versicolor
100           6.3          3.3           6.0          2.5   Iris-virginica
101           5.8          2.7           5.1          1.9   Iris-virginica
102           7.1          3.0           5.9          2.1   Iris-virginica
103           6.3          2.9           5.6          1.8   Iris-virginica
104           6.5          3.0           5.8          2.2   Iris-virginica
105           7.6          3.0           6.6          2.1   Iris-virginica
107           7.3          2.9           6.3          1.8   Iris-virginica
108           6.7          2.5           5.8          1.8   Iris-virginica
109           7.2          3.6           6.1          2.5   Iris-virginica
110           6.5          3.2           5.1          2.0   Iris-virginica
111           6.4          2.7           5.3          1.9   Iris-virginica
112           6.8          3.0           5.5          2.1   Iris-virginica
113           5.7          2.5           5.0          2.0   Iris-virginica
114           5.8          2.8           5.1          2.4   Iris-virginica
115           6.4          3.2           5.3          2.3   Iris-virginica
116           6.5          3.0           5.5          1.8   Iris-virginica
117           7.7          3.8           6.7          2.2   Iris-virginica
118           7.7          2.6           6.9          2.3   Iris-virginica
119           6.0          2.2           5.0          1.5   Iris-virginica
120           6.9          3.2           5.7          2.3   Iris-virginica
122           7.7          2.8           6.7          2.0   Iris-virginica
124           6.7          3.3           5.7          2.1   Iris-virginica
125           7.2          3.2           6.0          1.8   Iris-virginica
128           6.4          2.8           5.6          2.1   Iris-virginica
129           7.2          3.0           5.8          1.6   Iris-virginica
130           7.4          2.8           6.1          1.9   Iris-virginica
131           7.9          3.8           6.4          2.0   Iris-virginica
132           6.4          2.8           5.6          2.2   Iris-virginica
133           6.3          2.8           5.1          1.5   Iris-virginica
134           6.1          2.6           5.6          1.4   Iris-virginica
135           7.7          3.0           6.1          2.3   Iris-virginica
136           6.3          3.4           5.6          2.4   Iris-virginica
137           6.4          3.1           5.5          1.8   Iris-virginica
139           6.9          3.1           5.4          2.1   Iris-virginica
140           6.7          3.1           5.6          2.4   Iris-virginica
141           6.9          3.1           5.1          2.3   Iris-virginica
142           5.8          2.7           5.1          1.9   Iris-virginica
143           6.8          3.2           5.9          2.3   Iris-virginica
144           6.7          3.3           5.7          2.5   Iris-virginica
145           6.7          3.0           5.2          2.3   Iris-virginica
146           6.3          2.5           5.0          1.9   Iris-virginica
147           6.5          3.0           5.2          2.0   Iris-virginica
148           6.2          3.4           5.4          2.3   Iris-virginica
149           5.9          3.0           5.1          1.8   Iris-virginica

In [65]:
top = df.sort_values('petal_length', ascending=False)
print(top[['species', 'petal_length']])

            species  petal_length
118  Iris-virginica           6.9
117  Iris-virginica           6.7
122  Iris-virginica           6.7
105  Iris-virginica           6.6
131  Iris-virginica           6.4
..              ...           ...
41      Iris-setosa           1.3
35      Iris-setosa           1.2
14      Iris-setosa           1.2
13      Iris-setosa           1.1
22      Iris-setosa           1.0

[150 rows x 2 columns]

In [66]:
print('--- HEAD ---')
print(df.head())

print('--- TAIL ---')
print(df.tail())

print('--- SHAPE ---')
print(df.shape)

print('--- COLUMNS ---')
print(list(df.columns))

print('--- INFO ---')
df.info()

print('--- DESCRIBE ---')
print(df.describe())

print('--- DTYPES ---')
print(df.dtypes)

print('--- MISSING ---')
print(df.isnull().sum())

print('--- DUPLICATES ---')
print(df.duplicated().sum())

--- HEAD ---
   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa
--- TAIL ---
     sepal_length  sepal_width  petal_length  petal_width         species
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica
--- SHAPE ---
(150, 5)
--- COLUMNS ---
['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'species']
--- INFO ---
<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    str
dtypes: float64(4), str(1)
memory usage: 7.9 KB
--- DESCRIBE ---
       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000
--- DTYPES ---
sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
species             str
dtype: object
--- MISSING ---
sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64
--- DUPLICATES ---
3

In [67]:
def inspect_dataset(df):
    print('DATASET HEALTH CHECK')
    print('Rows:', df.shape[0])
    print('Columns:', df.shape[1])
    print('Column names:', list(df.columns))

    print('\nMissing values:')
    print(df.isnull().sum())

    print('\nDuplicate rows:')
    print(df.duplicated().sum())

    print('\nData types:')
    print(df.dtypes)

    print('\nFirst rows:')
    print(df.head())

inspect_dataset(df)

DATASET HEALTH CHECK
Rows: 150
Columns: 5
Column names: ['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'species']

Missing values:
sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

Duplicate rows:
3

Data types:
sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
species             str
dtype: object

First rows:
   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa